---

disable_rhui: true

up2date_system: true

rhsm_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-ose-3.7-rpms
  - rh-gluster-3-for-rhel-7-server-rpms

...
