---

- name: look for local ssh private key
  stat:
    path: "{{ playbook_dir }}/fetch/id_rsa"
  register: private_key
  delegate_to: localhost

- name: look for local ssh public key
  stat:
    path: "{{ playbook_dir }}/fetch/id_rsa.pub"
  register: public_key
  delegate_to: localhost

- block:
  - name: create ssh key pair for internal use
    shell:
      cmd: ssh-keygen -b 2048 -t rsa -f /home/ec2-user/.ssh/id_rsa -q -N ""
      creates: /home/ec2-user/.ssh/id_rsa

  - name: change permissions on key pair
    file: path=/home/ec2-user/.ssh/{{ item }} owner=ec2-user group=ec2-user mode=0400
    with_items:
      - id_rsa
      - id_rsa.pub

  - name: fetch ssh pub key
    fetch:
      src: /home/ec2-user/.ssh/id_rsa.pub
      dest: fetch/
      flat: yes

  - name: fetch ssh private key
    fetch:
      src: /home/ec2-user/.ssh/id_rsa
      dest: fetch/
      flat: yes
  when:
    - not private_key.stat.exists or not public_key.stat.exists

- name: add ssh key pair to authorized_keys
  authorized_key:
    user: ec2-user
    key: "{{ lookup('file', 'fetch/id_rsa.pub') }}"
    state: present

- name: set up ssh keys for ec2-user
  copy:
    src: fetch/{{ item }}
    dest: /home/ec2-user/.ssh/
    owner: ec2-user
    group: ec2-user
    mode: 0400
  with_items:
    - id_rsa
    - id_rsa.pub
  when:
    - private_key.stat.exists
    - public_key.stat.exists

...
