---

- name: disable hostname control in cloud-init
  lineinfile:
    regexp: '^ - {{ item }}'
    line: "{{ item }}"
    dest: /etc/cloud/cloud.cfg
    state: absent
  with_items:
    - set_hostname
    - update_hostname

- name: copy cfn-signal.sh script to /usr/local/sbin
  copy:
    src: cfn-signal.sh
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: 0755

...
