site_name: Container-Native Storage 3.6 on OpenShift Container Platform 3.7 Hands-on Lab
site_url: 'https://dmesser.github.io/ocp-3.7-cns-3.6-lab/'
copyright: 'Copyright ©2018 Red Hat, Inc.'

theme:
  name: 'material'
  logo: 'img/shadowman_rgb.png'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  feature:
    tabs: true

pages:
- Overview: index.md
- Modules:
    - 'Module 1 - OpenShift Environment': module-1-ocp-environment.md
    - 'Module 2 - Deploying Container-Native Storage': module-2-deploy-cns.md
    - 'Module 3 - Persistent Storage for Apps': module-3-cns-for-apps.md
    - 'Module 4 - Cluster Operations': module-4-cluster-ops.md
    - 'Module 5 - Persistent Storage for Infrastructure': module-5-cns-for-infra.md

markdown_extensions:
    - smarty
    - toc:
        permalink: '#'
    - sane_lists
    - footnotes
    - smart_strong
    - nl2br
    - codehilite:
        guess_lang: False
    - admonition
